baseURL = 'https://jared.today'
languageCode = 'en-us'
title = 'Jared Today'
theme = 'prickly-pear'

[params]
    colortheme = "white"
    description = "This is a sample piece of text for the description"
    mainSection = "posts"
    mainSectionTitle = "Writings"
    dateFormat = "2006-01-02" # default
    showReadTime = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

staticDir = ['static']